/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#0054d6",
        "surface-variant": "#e0e3e6",
        "surface-bright": "#f7f9fc",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-container": "#cc4204",
        "inverse-primary": "#b3c5ff",
        "outline-variant": "#c2c6d8",
        "on-surface": "#191c1e",
        "on-primary-fixed": "#001849",
        "inverse-surface": "#2d3133",
        "surface-container-low": "#f2f4f7",
        "secondary-fixed": "#e1e3e4",
        "on-surface-variant": "#424656",
        "tertiary-fixed": "#ffdbd0",
        "tertiary": "#a33200",
        "tertiary-fixed-dim": "#ffb59d",
        "secondary-container": "#e1e3e4",
        "primary-fixed-dim": "#b3c5ff",
        "on-tertiary": "#ffffff",
        "secondary": "#5c5f60",
        "on-tertiary-fixed": "#390c00",
        "primary-container": "#0066ff",
        "on-secondary-container": "#626566",
        "on-secondary-fixed": "#191c1d",
        "inverse-on-surface": "#eff1f4",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#454748",
        "secondary-fixed-dim": "#c5c7c8",
        "error": "#ba1a1a",
        "surface-container-highest": "#e0e3e6",
        "on-primary-fixed-variant": "#003fa4",
        "on-primary-container": "#f8f7ff",
        "primary": "#0050cb",
        "surface-container-high": "#e6e8eb",
        "on-background": "#191c1e",
        "surface-container": "#eceef1",
        "surface": "#f7f9fc",
        "outline": "#727687",
        "surface-dim": "#d8dadd",
        "primary-fixed": "#dae1ff",
        "background": "#f7f9fc",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#832600",
        "on-tertiary-container": "#fff6f4"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
